my_theme:
    resource: "@MyThemeBundle/Resources/config/routing.yml"
    prefix:   /

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin_home:
    path: /profile
    defaults: {_controller: AvanzuAdminThemeBundle:Default:index}
    options:
        avanzu_admin_route: welcome